name: Ensure compliance with Ledger guidelines

# This workflow is mandatory in all applications
# It calls a reusable workflow guidelines_enforcer developed by Ledger's internal developer team.
# The successful completion of the reusable workflow is a mandatory step for an app to be available on the Ledger
# application store.
#
# More information on the guidelines can be found in the repository:
# LedgerHQ/ledger-app-workflows/

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - master # for safety reasons
      - dev  # for safety reasons
  pull_request:

jobs:
  setup_and_install:
    name: Setup Python and Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          make deps

  guidelines_enforcer:
    name: Call Ledger guidelines_enforcer
    needs: setup_and_install
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_guidelines_enforcer.yml@v1
    with:
      python-version: '3.10'
