name: Build_NanoS
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
      - develop
      - master # for safety reasons
      - dev  # for safety reasons

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'v104.63001.3'
          submodules: true
      - name: Install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          make deps

  build_ledger:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/nanos-secure-sdk
    outputs:
      size: ${{steps.build.outputs.size}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'v104.63001.3'
          submodules: true
      - name: Build Standard app
        id: build
        shell: bash -l {0}
        run: |
          SUBSTRATE_PARSER_FULL=1 make
          echo "size=$(python3 deps/ledger-zxlib/scripts/getSize.py s)" >> $GITHUB_OUTPUT

  size_nano_s:
    needs: build_ledger
    runs-on: ubuntu-latest
    env:
      NANOS_LIMIT_SIZE: 136
    steps:
      - run: |
          echo "LNS app size: ${{needs.build_ledger.outputs.size}} KiB"
          [ ${{needs.build_ledger.outputs.size}} -le $NANOS_LIMIT_SIZE ]

  build_package_nanos_xl:
    needs: [configure, build, build_ledger]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/nanos-secure-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'v104.63001.3'
          submodules: true
      - name: Install deps
        run: pip install ledgerblue

      - name: Build NanoS XL
        shell: bash -l {0}
        run: |
          make SUBSTRATE_PARSER_FULL=1 PRODUCTION_BUILD=0
          mv ./app/pkg/installer_s.sh ./app/pkg/installer_nanos_xl.sh
      - name: Set tag
        id: nanos_xl
        run: echo "tag_name=$(./app/pkg/installer_nanos_xl.sh version)" >> $GITHUB_OUTPUT
      - name: Update Release
        id: update_release_1
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          files: ./app/pkg/installer_nanos_xl.sh
          tag_name: ${{ steps.nanos_xl.outputs.tag_name }}
          draft: false
          prerelease: false
